import React from 'react';
import './ContactAboutStyles.scss';

function AboutUs() {

  return(
    <div className='aboutWhole'>
      <h1>About Us Test</h1>
      <div className='aboutText'>
        <p>
          Mr. Goetz is a recognized expert in the field of urban land management, landscape planning & construction and urban forestry. Mr. Goetz holds degrees in both Forestry and Landscape Architecture. He is a member of the American Society of Consulting Arborists, Registration Number 260, the American Society of Landscape Architects, Oregon Registration Number 80 and the Society of American Foresters. Mr. Goetz's current practice emphasizes cost effective stewardship of client properties and projects. This is accomplished by preserving suitable indigenous vegetation if appropriate, assisting in the planning, design and construction of site improvements, natural features and landscape amenities that are compatible with physical conditions present on the finished project. This is followed by recommendations on landscape maintenance techniques that ensure the survival and growth of the landscape plants and supports the desired performance of site improvements, all at reasonable cost. Over the long-term this maximizes the return on a client’s investment in project development and annual operating costs.
        </p>
        <p>
          Prior to relocating to Oregon, he developed and/or oversaw natural resource management, land management and urban forestry programs for a number of public and private sector clients in the mid-western states and Canada. For over ten years he was employed by the City of Portland, first as City Forester and later as Park Grounds & Operations Manager where he provided similar services for public agencies in the Portland metropolitan area. While with the City of Portland, Mr. Goetz directed the largest tree and landscape maintenance organization in the Pacific Northwest. For both public and private clients, he has over seen the expenditure of over $281 million and over 7.85 million man hours directed at the care and installation of trees, shrubs, lawn and other landscape elements on over 13,000 acres of public and private property. Mr. Goetz has provided services in all aspects of landscape planning and management programs. This included project management, land use planning, site planning and design, maintenance planning, site vegetation assessment, natural resource planning and restoration (forests, wetlands, quarries, sand & gravel sites, lakes and streams), supervision of landscape construction and restoration and administering maintenance contracts.
        </p>
        <p>
          Mr. Goetz also provides appraisals for a wide range of ornamental landscape plants and agricultural crops. During his career, he has evaluated and prepared appraisals for millions of trees, landscape or nursery plants and agricultural crops that are offered for sale, security or liquidation. This includes appraisal values ranging from several hundred to over 35 million dollars for plants in crop or nursery production and those damaged or lost due to storms, fires, accidents, vandalism or which have depreciated in value due to factors such as fire, chemical injury, deficient landscape design, improper construction, improper maintenance practices or other factors. He has testified for or prepared appraisals for litigation in municipal, state and federal court. These cases involved bankruptcy, condemnation, property damage, and personal injury involving trees and landscape plants, for both public and private clients in the United States and Canada. Mr. Goetz has also been called upon by the International Society of Arboriculture to teach beginning and advanced plant appraisal courses and to chair the Pacific Northwest Regional Plant Appraisal Committee that determines the species ratings and basic values used in the Council of Tree & Landscape Appraisers appraisal methodology. 
        </p>
        <p>
          A few of the public sector clients that have sought his assistance include the Oregon cities of Portland, Lake Oswego, Hillsboro, Wilsonville, Klamath Falls, Bend, Eugene, Medford, The Dalles; Washington cities of Seattle, Brier, Bellevue, Everett, Renton, Tukwila, Vancouver, Washougal & Camas, and Canadian cities of Vancouver, BC, Victoria, BC. Other public clients include the Oregon and Washington Departments of Transportation, Oregon Department of Agriculture, Oregon Department of Forestry, Washington Department of Natural Resources, Port of Portland, TriMet, Portland Public Schools, Portland Development Commission and the USDA Forest Service & Secretary of Agriculture. Some of the his private sector clients include companies which own, manage, insure, invest in or care for both natural and ornamental landscaped sites including; BOEING, PacificCorp, Portland General Electric, NW Natural Gas, NIKE, Microsoft, Weyerhauser, Asplundh Tree Experts, Portland Golf Club, Lake Oswego Country Club, Safeco Insurance, State Farm Insurance, Allstate Insurance, Fireman's Fund Insurance, USF & G Insurance, US Bank, Bank of America, Cort-MacKenzie Securities, Paul Allen Enterprises, InFocus, Lattice Semiconductor, Tektronix, PACTRUST, OPUS, Ashforth Pacific, Equity Office, Shorenstein Properties, Trammell Crow, Beaux Frères Winery, Domaine Serene Winery, Duck Pond Cellars and Ross Island Sand & Gravel. 
        </p>
        <p>
          Working with his associates Mr. Goetz's firm provides a broad range of expertise to deal with any kind of land or vegetation management project.  His clients have benefited in one or more of the following: reduced site development costs, reduced site maintenance costs, improved quality and frequency of maintenance service, reduced losses of site vegetation, improved aesthetic appearance, reduced time in legal or property dispute resolution, reduced time in development permitting and public review and reduced time of facilities or property management staff in dealing with landscape issues.
        </p>
      </div>
    </div>
  )
}

export default AboutUs;